package handler

import (
	"encoding/json"
	"net/http"

	"inventory-system/internal/dto/request"
	"inventory-system/internal/service"
	"inventory-system/pkg/utils"

	"github.com/go-chi/chi/v5/middleware"
	"go.uber.org/zap"
)

// AuthHandler defines the HTTP endpoints for authentication-related operations.
type AuthHandler interface {
	// Login handles user authentication and returns a JWT token upon success.
	Login(w http.ResponseWriter, r *http.Request)
}

// authHandler is the concrete implementation of AuthHandler.
type authHandler struct {
	authService service.AuthService
	logger      *zap.Logger
}

// NewAuthHandler creates and returns a new instance of AuthHandler.
func NewAuthHandler(authService service.AuthService, logger *zap.Logger) AuthHandler {
	return &authHandler{
		authService: authService,
		logger:      logger,
	}
}

// Login godoc
// @Summary      User Login
// @Description  Authenticate user with email and password, and return a JWT token.
// @Tags         Authentication
// @Accept       json
// @Produce      json
// @Param        request body request.LoginRequest true "Login credentials"
// @Success      200  {object}  utils.Response{data=response.AuthResponse} "Login successful"
// @Failure      400  {object}  utils.Response "Invalid request format"
// @Failure      401  {object}  utils.Response "Invalid email or password"
// @Failure      500  {object}  utils.Response "Internal server error"
// @Router       /api/v1/login [post]
func (h *authHandler) Login(w http.ResponseWriter, r *http.Request) {
	// Extract the unique Request ID generated by the Chi middleware.
	// This ID is used for tracing the request across the application layers.
	reqID := middleware.GetReqID(r.Context())

	var req request.LoginRequest

	// 1. Decode the JSON payload from the request body into the DTO.
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		h.logger.Warn("Failed to decode login request body",
			zap.String("request_id", reqID),
			zap.Error(err),
		)
		utils.Error(w, r, http.StatusBadRequest, "Invalid request format", nil)
		return
	}

	// 2. Pass the decoded request to the Service layer for business logic processing.
	res, err := h.authService.Login(r.Context(), req)
	if err != nil {
		// Handle expected business errors (e.g., wrong credentials)
		if err.Error() == "invalid email or password" {
			h.logger.Warn("Unauthorized login attempt", zap.String("request_id", reqID), zap.String("email", req.Email))
			utils.Error(w, r, http.StatusUnauthorized, err.Error(), nil)
			return
		}

		// Handle unexpected system errors (e.g., database down, JWT generation failed)
		h.logger.Error("Internal server error during login", zap.String("request_id", reqID), zap.Error(err))
		utils.Error(w, r, http.StatusInternalServerError, "Internal server error", nil)
		return
	}

	// 3. If successful, return the HTTP 200 OK response with the generated token and user data.
	h.logger.Info("Login request processed successfully", zap.String("request_id", reqID))
	utils.Success(w, r, http.StatusOK, "Login successful", res)
}
